CLASS zcx_dbbr_node_not_found DEFINITION
  PUBLIC
  INHERITING FROM zcx_sat_nc_exception
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_dbbr_node_not_found IMPLEMENTATION.
ENDCLASS.
