INTERFACE zif_dbbr_c_input_type
  PUBLIC.


  CONSTANTS text_input TYPE i VALUE 0 ##NO_TEXT.
  CONSTANTS checkbox TYPE i VALUE 1 ##NO_TEXT.
  CONSTANTS dropdown TYPE i VALUE 2 ##NO_TEXT.
ENDINTERFACE.
