INTERFACE zif_dbbr_c_favmenu_type
  PUBLIC .

  CONSTANTS table    TYPE ZSAT_FAVMENU_TYPE VALUE 'T' ##no_text.
  CONSTANTS query   TYPE ZSAT_FAVMENU_TYPE VALUE 'Q' ##no_text.
  CONSTANTS cds_view TYPE ZSAT_FAVMENU_TYPE VALUE 'C' ##no_text.
  CONSTANTS folder   TYPE ZSAT_FAVMENU_TYPE VALUE 'O' ##no_text.
  CONSTANTS view   TYPE ZSAT_FAVMENU_TYPE VALUE 'V' ##no_text.

ENDINTERFACE.
