interface ZIF_DBBR_C_JOIN_COND_VAL_TYPE
  public .


  constants SYSTEM_VALUE_INPUT type ZDBBR_JOIN_COND_VALUE_TYPE value 'SYSTEM' ##NO_TEXT.
  constants TYPED_INPUT type ZDBBR_JOIN_COND_VALUE_TYPE value 'TYPED' ##NO_TEXT.
  constants PARAMETER_INPUT type ZDBBR_JOIN_COND_VALUE_TYPE value 'PARAM' ##NO_TEXT.
endinterface.
