*"* use this source file for any type of declarations (class
*"* definitions, interfaces or type declarations) you need for
*"* components in the private section
INTERFACE lif_selfield_names.
  CONSTANTS c_tabname TYPE dynfnam VALUE 'GS_SELFIELDS-TABNAME'.
  CONSTANTS c_tabname_alias TYPE dynfnam VALUE 'GS_SELFIELDS-TABNAME_ALIAS'.
  CONSTANTS c_fieldname TYPE dynfnam VALUE 'GS_SELFIELDS-FIELDNAME'.
  CONSTANTS c_fieldname_raw TYPE dynfnam VALUE 'GS_SELFIELDS-FIELDNAME_RAW'.
  CONSTANTS c_alias TYPE dynfnam VALUE 'GS_SELFIELDS-ALIAS'.
  CONSTANTS c_entry TYPE dynfnam VALUE 'GS_SELFIELDS-ENTRY'.
  CONSTANTS c_sign TYPE dynfnam VALUE 'GS_SELFIELDS-SIGN'.
  CONSTANTS c_option TYPE dynfnam VALUE 'GS_SELFIELDS-OPTION'.
  CONSTANTS c_low TYPE dynfnam VALUE 'GS_SELFIELDS-LOW'.
  CONSTANTS c_high TYPE dynfnam VALUE 'GS_SELFIELDS-HIGH'.
  CONSTANTS c_type TYPE dynfnam VALUE 'GS_SELFIELDS-TYPE'.
  CONSTANTS c_outputlen TYPE dynfnam VALUE 'GS_SELFIELDS-OUTPUTLEN'.
  CONSTANTS c_intlen TYPE dynfnam VALUE 'GS_SELFIELDS-INTLEN'.
  CONSTANTS c_convexit TYPE dynfnam VALUE 'GS_SELFIELDS-CONVEXIT'.
  CONSTANTS c_description TYPE dynfnam VALUE 'GS_SELFIELDS-DESCRIPTION'.
  CONSTANTS c_scrtext_m TYPE dynfnam VALUE 'GS_SELFIELDS-SCRTEXT_M'.
  CONSTANTS c_scrtext_l TYPE dynfnam VALUE 'GS_SELFIELDS-SCRTEXT_L'.
  CONSTANTS c_ddtext TYPE dynfnam VALUE 'GS_SELFIELDS-DDTEXT'.
  CONSTANTS c_datatype TYPE dynfnam VALUE 'GS_SELFIELDS-DATATYPE'.
  CONSTANTS c_inttype TYPE dynfnam VALUE 'GS_SELFIELDS-INTTYPE'.
  CONSTANTS c_is_numeric TYPE dynfnam VALUE 'GS_SELFIELDS-IS_NUMERIC'.
  CONSTANTS c_key TYPE dynfnam VALUE 'GS_SELFIELDS-KEY'.
  CONSTANTS c_push TYPE dynfnam VALUE 'GS_SELFIELDS-PUSH'.
  CONSTANTS c_input TYPE dynfnam VALUE 'GS_SELFIELDS-INPUT'.
  CONSTANTS c_client TYPE dynfnam VALUE 'GS_SELFIELDS-CLIENT'.
  CONSTANTS c_rollname TYPE dynfnam VALUE 'GS_SELFIELDS-ROLLNAME'.
  CONSTANTS c_domname TYPE dynfnam VALUE 'GS_SELFIELDS-DOMNAME'.
  CONSTANTS c_lowercase TYPE dynfnam VALUE 'GS_SELFIELDS-LOWERCASE'.
  CONSTANTS c_low_noconv TYPE dynfnam VALUE 'GS_SELFIELDS-LOW_NOCONV'.
  CONSTANTS c_high_noconv TYPE dynfnam VALUE 'GS_SELFIELDS-HIGH_NOCONV'.
  CONSTANTS c_group_by TYPE dynfnam VALUE 'GS_SELFIELDS-GROUP_BY'.
  CONSTANTS c_aggregation TYPE dynfnam VALUE 'GS_SELFIELDS-AGGREGATION'.
  CONSTANTS c_is_table_header TYPE dynfnam VALUE 'GS_SELFIELDS-IS_TABLE_HEADER'.
  CONSTANTS c_has_cust_f4_help TYPE dynfnam VALUE 'GS_SELFIELDS-HAS_CUST_F4_HELP'.
  CONSTANTS c_f4_info TYPE dynfnam VALUE 'GS_SELFIELDS-F4_INFO'.
  CONSTANTS c_f4_available TYPE dynfnam VALUE 'GS_SELFIELDS-F4_AVAILABLE'.
  CONSTANTS c_ddic_order TYPE dynfnam VALUE 'GS_SELFIELDS-DDIC_ORDER'.
  CONSTANTS c_system_value_type TYPE dynfnam VALUE 'GS_SELFIELDS-SYSTEM_VALUE_TYPE'.
  CONSTANTS c_has_subquery TYPE dynfnam VALUE 'GS_SELFIELDS-HAS_SUBQUERY'.
  CONSTANTS c_subquery TYPE dynfnam VALUE 'GS_SELFIELDS-SUBQUERY'.
  CONSTANTS c_subquery_mode TYPE dynfnam VALUE 'GS_SELFIELDS-SUBQUERY_MODE'.
  CONSTANTS c_tree_collapsed TYPE dynfnam VALUE 'GS_SELFIELDS-TREE_COLLAPSED'.
ENDINTERFACE.


INTERFACE lif_global_data_consts.
  CONSTANTS c_no_html_header TYPE dynfnam VALUE 'GS_DATA-NO_HTML_HEADER'.
  CONSTANTS c_alv_variant TYPE dynfnam VALUE 'GS_DATA-ALV_VARIANT'.
  CONSTANTS c_del_whole_line TYPE dynfnam VALUE 'GS_DATA-DEL_WHOLE_LINE'.
  CONSTANTS c_join_key TYPE dynfnam VALUE 'GS_DATA-JOIN_KEY'.
  CONSTANTS c_color_sort_columns TYPE dynfnam VALUE 'GS_DATA-COLOR_SORT_COLUMNS'.
  CONSTANTS c_or_selection TYPE dynfnam VALUE 'GS_DATA-OR_SELECTION'.
  CONSTANTS c_tech_names TYPE dynfnam VALUE 'GS_DATA-TECH_NAMES'.
  CONSTANTS c_cwidth_opt_off TYPE dynfnam VALUE 'GS_DATA-CWIDTH_OPT_OFF'.
  CONSTANTS c_no_merging_on TYPE dynfnam VALUE 'GS_DATA-NO_MERGING_ON'.
  CONSTANTS c_no_convexit TYPE dynfnam VALUE 'GS_DATA-NO_CONVEXIT'.
  CONSTANTS c_zero_val_as_blank TYPE dynfnam VALUE 'GS_DATA-ZERO_VAL_AS_BLANK'.
  CONSTANTS c_tech_first TYPE dynfnam VALUE 'GS_DATA-TECH_FIRST'.
  CONSTANTS c_tech_view TYPE dynfnam VALUE 'GS_DATA-TECH_VIEW'.
  CONSTANTS c_max_lines TYPE dynfnam VALUE 'GS_DATA-MAX_LINES'.
  CONSTANTS c_no_trailing_sign TYPE dynfnam VALUE 'GS_DATA-NO_TRAILING_SIGN'.
  CONSTANTS c_emphasize_text_fields TYPE dynfnam VALUE 'GS_DATA-EMPHASIZE_TEXT_FIELDS'.
  CONSTANTS c_key_cols_not_fixed TYPE dynfnam VALUE 'GS_DATA-KEY_COLS_NOT_FIXED'.
  CONSTANTS c_fav_user_mode TYPE dynfnam VALUE 'GS_DATA-FAV_USER_MODE'.
  CONSTANTS c_use_reduced_memory TYPE dynfnam VALUE 'GS_DATA-USE_REDUCED_MEMORY'.
  CONSTANTS c_auto_layout_transfer TYPE dynfnam VALUE 'GS_DATA-AUTO_LAYOUT_TRANSFER'.
  CONSTANTS c_advanced_mode TYPE dynfnam VALUE 'GS_DATA-ADVANCED_MODE'.
  CONSTANTS c_favmenu_expanded TYPE dynfnam VALUE 'GS_DATA-FAVMENU_EXPANDED'.
  CONSTANTS c_last_used_count TYPE dynfnam VALUE 'GS_DATA-LAST_USED_COUNT'.
  CONSTANTS c_primary_table TYPE dynfnam VALUE 'GS_DATA-PRIMARY_TABLE'.
  CONSTANTS c_alv_varianttext TYPE dynfnam VALUE 'GS_DATA-ALV_VARIANTTEXT'.
  CONSTANTS c_join_key_text TYPE dynfnam VALUE 'GS_DATA-JOIN_KEY_TEXT'.
  CONSTANTS c_edit TYPE dynfnam VALUE 'GS_DATA-EDIT'.
  CONSTANTS c_client_dependent TYPE dynfnam VALUE 'GS_DATA-CLIENT_DEPENDENT'.
  CONSTANTS c_tab_save TYPE dynfnam VALUE 'GS_DATA-TAB_SAVE'.
  CONSTANTS c_delete_mode TYPE dynfnam VALUE 'GS_DATA-DELETE_MODE'.
ENDINTERFACE.
